/*
 * This source file was generated by the Gradle 'init' task
 */
package clientgradle;

import java.io.IOException;
import static clientgradle.Simple_Client.*;

public class App {
    public static void main(String[] args) throws IOException {
        // to allow changing the host, if the server is not running on localhost
        if(args.length == 1){ 
            Simple_Client.host = args[0];
            System.out.println("Host changed to: " + Simple_Client.host);
        }
        System.out.println("Actual Host: " + Simple_Client.host);
        //TODO: can the server send gRPC messages to the client? and the client respond?
        // If yes, we could also test how the client responds to the server's messages
        test_get("/", 200, "Server is running");
        test_get("/health", 200, "Controller is Healthy");
        test_get("/unknown", 404, "Not Found");

        test_post("/", "{\"dummy_data\": \"Uebung 3.2 is ready\"}", 200, "Data received and stored");
        test_post_with_rtt("/", "{\"dummy_data\":\"rtt testing\"}", 200, "Data received and stored");
    }
}
