/*
 * This source file was generated by the Gradle 'init' task
 */
package clientgradle;

import java.io.IOException;
import static clientgradle.Simple_Client.*;

public class App {
    public static void main(String[] args) throws IOException {
        // to allow changing the host, if the server is not running on localhost
        if(args.length == 1){ 
            Simple_Client.host = args[0];
            System.out.println("Actual Host: " + Simple_Client.host);
        }
        test_get("/reset", 205, "");
        test_get("/", 200, "Server is running");
        test_get("/status", 200,
                "{\"robots_active\": 5, \"current_captain\": \"Captain A\", \"controller_status\": \"Healthy\", \"dummy_data\": \"\"}");
        test_get("/captain", 200, "{\"captain\": \"Captain A\"}");
        test_get("/health", 200, "Controller is Healthy");
        test_get("/election", 200, "New captain elected: Captain B");
        test_get("/unknown", 404, "Not Found");

        test_post("/", "{\"dummy_data\": \"test data\"}", 200, "Data received and stored");
    }
}
