services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    image: ds-gr15/server
    container_name: server_container
    ports:
      - "8080:8080"  # Exposes HTTP server port
      - "50051:50051"  # Exposes gRPC server port
    restart: always  # Ensures the container restarts automatically if it stops
    networks:
      static_network:
        ipv4_address: 192.168.1.100  # Assigns a static IP to the server

  robot:
    build:
      context: .
      dockerfile: Robot/Dockerfile
    image: ds-gr15/robot
    depends_on:
      - server
    networks:
      - static_network
    environment:
      - TARGET_SERVER=192.168.1.100
    stdin_open: true  # Keeps stdin open (prevents EOFError)
    tty: true  # Allocates a terminal for interactive input
    command: ["/bin/sh", "-c", "exec python3 robot.py robot_$(hostname)"]

  client:
    build:
      context: .
      dockerfile: Client/Dockerfile
    image: ds-gr15/client
    container_name: client_container
    depends_on:
      - server
    networks:
      - static_network

networks:
  static_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24  # Defines the subnet for the network
