syntax = "proto3";

service RobotController {
  rpc RegisterRobot (RobotInfo) returns (RegistrationResponse);
  rpc SendStatus (RobotStatus) returns (StatusResponse);
  rpc ElectCaptain (ElectionRequest) returns (ElectionResponse);
  rpc UnregisterRobot (RobotInfo) returns (RegistrationResponse);
  rpc RegisterCaptain (RobotInfo) returns (RegistrationResponse);
}

message RobotInfo {
  string id = 1;
}

message RegistrationResponse {
  string message = 1;
}

message RobotStatus {
  string id = 1;
  string status = 2;
}

message StatusResponse {
  string message = 1;
}

message ElectionRequest {}

message ElectionResponse {
  string id = 1;
}
