# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_controller_pb2 as robot__controller__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in robot_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterRobot = channel.unary_unary(
                '/RobotController/RegisterRobot',
                request_serializer=robot__controller__pb2.RobotInfo.SerializeToString,
                response_deserializer=robot__controller__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.SendStatus = channel.unary_unary(
                '/RobotController/SendStatus',
                request_serializer=robot__controller__pb2.RobotStatus.SerializeToString,
                response_deserializer=robot__controller__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ElectCaptain = channel.unary_unary(
                '/RobotController/ElectCaptain',
                request_serializer=robot__controller__pb2.ElectionRequest.SerializeToString,
                response_deserializer=robot__controller__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.UnregisterRobot = channel.unary_unary(
                '/RobotController/UnregisterRobot',
                request_serializer=robot__controller__pb2.RobotInfo.SerializeToString,
                response_deserializer=robot__controller__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.RegisterCaptain = channel.unary_unary(
                '/RobotController/RegisterCaptain',
                request_serializer=robot__controller__pb2.RobotInfo.SerializeToString,
                response_deserializer=robot__controller__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.CaptainStatus = channel.unary_unary(
                '/RobotController/CaptainStatus',
                request_serializer=robot__controller__pb2.CaptainStatusRequest.SerializeToString,
                response_deserializer=robot__controller__pb2.RobotInfo.FromString,
                _registered_method=True)
        self.CheckElectionID = channel.unary_unary(
                '/RobotController/CheckElectionID',
                request_serializer=robot__controller__pb2.ElectionResponse.SerializeToString,
                response_deserializer=robot__controller__pb2.StatusResponse.FromString,
                _registered_method=True)


class RobotControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElectCaptain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCaptain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptainStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckElectionID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRobot,
                    request_deserializer=robot__controller__pb2.RobotInfo.FromString,
                    response_serializer=robot__controller__pb2.RegistrationResponse.SerializeToString,
            ),
            'SendStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStatus,
                    request_deserializer=robot__controller__pb2.RobotStatus.FromString,
                    response_serializer=robot__controller__pb2.StatusResponse.SerializeToString,
            ),
            'ElectCaptain': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectCaptain,
                    request_deserializer=robot__controller__pb2.ElectionRequest.FromString,
                    response_serializer=robot__controller__pb2.ElectionResponse.SerializeToString,
            ),
            'UnregisterRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterRobot,
                    request_deserializer=robot__controller__pb2.RobotInfo.FromString,
                    response_serializer=robot__controller__pb2.RegistrationResponse.SerializeToString,
            ),
            'RegisterCaptain': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCaptain,
                    request_deserializer=robot__controller__pb2.RobotInfo.FromString,
                    response_serializer=robot__controller__pb2.RegistrationResponse.SerializeToString,
            ),
            'CaptainStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptainStatus,
                    request_deserializer=robot__controller__pb2.CaptainStatusRequest.FromString,
                    response_serializer=robot__controller__pb2.RobotInfo.SerializeToString,
            ),
            'CheckElectionID': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckElectionID,
                    request_deserializer=robot__controller__pb2.ElectionResponse.FromString,
                    response_serializer=robot__controller__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RobotController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RobotController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RobotController/RegisterRobot',
            robot__controller__pb2.RobotInfo.SerializeToString,
            robot__controller__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RobotController/SendStatus',
            robot__controller__pb2.RobotStatus.SerializeToString,
            robot__controller__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ElectCaptain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RobotController/ElectCaptain',
            robot__controller__pb2.ElectionRequest.SerializeToString,
            robot__controller__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RobotController/UnregisterRobot',
            robot__controller__pb2.RobotInfo.SerializeToString,
            robot__controller__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCaptain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RobotController/RegisterCaptain',
            robot__controller__pb2.RobotInfo.SerializeToString,
            robot__controller__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptainStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RobotController/CaptainStatus',
            robot__controller__pb2.CaptainStatusRequest.SerializeToString,
            robot__controller__pb2.RobotInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckElectionID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RobotController/CheckElectionID',
            robot__controller__pb2.ElectionResponse.SerializeToString,
            robot__controller__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
