# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_controller.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'robot_controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16robot_controller.proto\"\x17\n\tRobotInfo\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14RegistrationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x0bRobotStatus\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"!\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x11\n\x0f\x45lectionRequest\"\x16\n\x14\x43\x61ptainStatusRequest\"\x1e\n\x10\x45lectionResponse\x12\n\n\x02id\x18\x01 \x01(\t2\xfe\x02\n\x0fRobotController\x12\x32\n\rRegisterRobot\x12\n.RobotInfo\x1a\x15.RegistrationResponse\x12+\n\nSendStatus\x12\x0c.RobotStatus\x1a\x0f.StatusResponse\x12\x33\n\x0c\x45lectCaptain\x12\x10.ElectionRequest\x1a\x11.ElectionResponse\x12\x34\n\x0fUnregisterRobot\x12\n.RobotInfo\x1a\x15.RegistrationResponse\x12\x34\n\x0fRegisterCaptain\x12\n.RobotInfo\x1a\x15.RegistrationResponse\x12\x32\n\rCaptainStatus\x12\x15.CaptainStatusRequest\x1a\n.RobotInfo\x12\x35\n\x0f\x43heckElectionID\x12\x11.ElectionResponse\x1a\x0f.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTINFO']._serialized_start=26
  _globals['_ROBOTINFO']._serialized_end=49
  _globals['_REGISTRATIONRESPONSE']._serialized_start=51
  _globals['_REGISTRATIONRESPONSE']._serialized_end=90
  _globals['_ROBOTSTATUS']._serialized_start=92
  _globals['_ROBOTSTATUS']._serialized_end=133
  _globals['_STATUSRESPONSE']._serialized_start=135
  _globals['_STATUSRESPONSE']._serialized_end=168
  _globals['_ELECTIONREQUEST']._serialized_start=170
  _globals['_ELECTIONREQUEST']._serialized_end=187
  _globals['_CAPTAINSTATUSREQUEST']._serialized_start=189
  _globals['_CAPTAINSTATUSREQUEST']._serialized_end=211
  _globals['_ELECTIONRESPONSE']._serialized_start=213
  _globals['_ELECTIONRESPONSE']._serialized_end=243
  _globals['_ROBOTCONTROLLER']._serialized_start=246
  _globals['_ROBOTCONTROLLER']._serialized_end=628
# @@protoc_insertion_point(module_scope)
