# https://hub.docker.com/_/alpine
FROM alpine:3.16

#TODO: why alpine is better than using pyhon image?

# install pip
RUN apk add --update-cache \
    py3-pip \
  && rm -rf /var/cache/apk/*

# create app directory
WORKDIR /code

# bundle app source
COPY . .

# our application will listen on port 5000 inside the container
EXPOSE 8080

# run the application
CMD ["python3","-u", "Simple_Server.py"]