# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_controller.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'robot_controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16robot_controller.proto\"#\n\tRobotInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"\'\n\x14RegistrationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x0bRobotStatus\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"!\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x10\n\x0e\x43\x61ptainRequest\"&\n\x0f\x43\x61ptainResponse\x12\x13\n\x0bnew_captain\x18\x01 \x01(\t2\xa5\x01\n\x0fRobotController\x12\x32\n\rRegisterRobot\x12\n.RobotInfo\x1a\x15.RegistrationResponse\x12+\n\nSendStatus\x12\x0c.RobotStatus\x1a\x0f.StatusResponse\x12\x31\n\x0c\x45lectCaptain\x12\x0f.CaptainRequest\x1a\x10.CaptainResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTINFO']._serialized_start=26
  _globals['_ROBOTINFO']._serialized_end=61
  _globals['_REGISTRATIONRESPONSE']._serialized_start=63
  _globals['_REGISTRATIONRESPONSE']._serialized_end=102
  _globals['_ROBOTSTATUS']._serialized_start=104
  _globals['_ROBOTSTATUS']._serialized_end=145
  _globals['_STATUSRESPONSE']._serialized_start=147
  _globals['_STATUSRESPONSE']._serialized_end=180
  _globals['_CAPTAINREQUEST']._serialized_start=182
  _globals['_CAPTAINREQUEST']._serialized_end=198
  _globals['_CAPTAINRESPONSE']._serialized_start=200
  _globals['_CAPTAINRESPONSE']._serialized_end=238
  _globals['_ROBOTCONTROLLER']._serialized_start=241
  _globals['_ROBOTCONTROLLER']._serialized_end=406
# @@protoc_insertion_point(module_scope)
